#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr -s 1920x1080 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             2
bspc config window_gap              12

bspc config split_ratio            0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
feh --bg-fill ~/Photos/wallpaper.jpg
bash ~/.config/polybar/launch.sh --forest
picom &
